config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#intro'
  get '/map' => 'pages#home'
  get '/profile', to: "pages#profile"
  devise_for :users
  resources :users, only: [:edit, :update, :delete, :show, :index] do
    resources :friends, only: [:create, :destroy]
  end
  resources :friends, only: [:update]
  resources :routes
  resources :nodes
  resources :events, only: [:index, :show, :create, :edit, :destroy ] do
  resources :participants, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :routes, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_name_lastname_username, against: [ :name, :lastname, :username ]

  # has_many :friends, dependent: :destroy
  has_many :user_friends, foreign_key: :user_friend_id, class_name: "Friend"
  has_many :friends, through: :user_friends
  # has_and_belongs_to_many :friends,  class_name: "User", join_table:  :friends, foreign_key: :user_id, association_foreign_key: :friend_user_id

  has_many :participants
  has_many :events, through: :routes

  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def events_joined
    ((Participant.where(user: self)).map { |participant| participant.event } + events).uniq
  end

  def friend_requests
    self.user_friends.where(accepted: false)
  end

  def friend?(friend)
    self.friend_list.each { |friendship| return true if friendship.user_id == friend.id || friendship.user_friend_id == friend.id}
    false
  end

  def friend_list
    self.user_friends.where(accepted: true) + Friend.where(user_id: self.id).where(accepted: true)
  end

  def profile_picture
    if self.photo.attached?
      return self.photo.key
    else
      return "pp.png"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if params[:query].blank?
      @users = User.all
    else
      @users = User.search_by_name_lastname_username(params[:query])
    end
  end

  def show
    @user = User.find(params[:id])
    redirect_to profile_path if current_user == @user
    @events = @user.events_joined
    @routes = @user.routes
    @request_sent = Friend.where(user_id: current_user).where(user_friend_id: params[:id])[0] 
    @request_received = Friend.where(user_id: params[:id]).where(user_friend_id: current_user)[0]
  end

  def edit
  end

  def update

  end

  def delete

  end

end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h2 class="bungee-font-m">Runners</h2>
<div class="friends-search mt-2">
    <%= form_tag users_path, method: :get, class: "search-box-home" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "search-input-home",
        placeholder: "Find a friend"
      %>
</div>
      <%= submit_tag "Search", class: "btn btn-dark center-button" %>
  <% end %>
</div>
<div id="user-list">
  <% @users.each do |f| %>
    <div>
      <%= link_to f do %>
        <div class="card-friend">
          <% if f.photo.attached? %>
            <%= cl_image_tag(f.photo.key, width: 600, height: 500, crop: :fill) %>
          <% else %>
            <%= image_tag("pp.png", width: 600, height: 500, crop: :fill)%>
          <% end %>
          <div class="card-friend-infos">
            <h2><%= f.name.capitalize %> <%= f.lastname.capitalize %> </h2>
            <p> @<%= f.username.capitalize %> </p>
            <p><%= f.email %> </p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="bottom-img-profile" style="background: linear-gradient(white, rgb(255,255,255), transparent), url(<%= image_path('city.png') %>);">
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container h-100">
  <div class="row h-100 justify-content-center align-items-center">
    <div class="card-image-friends">
      <div class="card-header">
        <div class="profile_pic">
        <% if @user.photo.attached? %>
          <%= cl_image_tag(@user.photo.key, crop: :fill) %>
        <% else %>
          <%= image_tag("pp.png", crop: :fill)%>
        <% end %>
        </div>
      </div>
      <div class="card-body">
        <div class="d-flex justify-content-center flex-column">
          <div class="name_container">
            <div class="username"><h4> @<%= @user.username %></h4> </div>
          </div>
          <div class="fullname"> <p> <%= @user.name %> <%= @user.lastname %></p></div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>

<div class="d-flex justify-content-center"><h2 class="bungee-font-small-friends">My events</h2></div>
<div class="container">
<div class="title-left m-3">
  <div class="routes_history_card">
    <% @events.each do |e| %>
      <div class="big-card-profile">
        <a href="/events/<%= e.id%>">
          <div class="card-event-profile">
          <% if e.photo.attached? %>
            <%= cl_image_tag(e.photo.key, width: 400, height: 300, crop: :fill) %>
          <% else %>
            <%= image_tag "test_6.jpg", width: 400, height: 300 %>
          <% end %>
            <div class="card-event-info h-100 p-2">
              <div>
                <h5><strong> <%= e.title %> </strong></h5>
              </div>
              <div class="d-flex justify-content-between">
                <p><strong>Distance: </strong><%= e.route.distance %> </p>
                <p><strong> From: </strong> <%= e.route.nodes.first.address.upcase %> </p>
                <p><strong> To: </strong> <%= e.route.form == "Circular" ? e.route.nodes.first.address.upcase : e.route.nodes.last.address.upcase %> </p>
              </div>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>
</div>

<div class="d-flex justify-content-center"><h2 class="bungee-font-small-friends">Friends</h2></div>
  <div class="row h-100 justify-content-center align-items-center">
    <div class="friends-photo">
      <% @user.friend_list.each do |f| %>
        <% if f.friend(@user).photo.attached? %>
          <%= cl_image_tag(f.friend(@user).photo.key) %>
        <% else %>
          <%= image_tag("pp.png")%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center">
  <div class="row">
    <% if current_user.friend?(@user) %>
      <%= link_to user_friends_path(@user), method: :post, remote: true do %>
        <button type="button" class="btn btn-danger fs-it-btn">
          <i class="fa fa-times" aria-hidden="true"></i>
          <span class="fs-it-btn-vertical-line"></span>
          Remove friend
        </button>
      <% end %>
    <% elsif @request_sent %>
      <%= link_to user_friends_path(@user), method: :post, remote: true do %>
        <button type="button" class="btn bg-blue fs-it-btn">
          <i class="fa fa-check" aria-hidden="true"></i>
          <span class="fs-it-btn-vertical-line"></span>
          Friend request sent!
        </button>
      <% end %>
    <% elsif @request_received %>
      <%= link_to friend_path(@user.id), method: :patch, remote: true do %>
        <button type="button" class="btn bg-blue fs-it-btn">
          <i class="fa fa-check" aria-hidden="true"></i>
          <span class="fs-it-btn-vertical-line"></span>
          Accept friend
        </button>
      <% end %>
    <% else %>
      <%= link_to user_friends_path(@user), method: :post, remote: true do %>
        <button type="button" class="btn bg-blue fs-it-btn">
          <i class="fa fa-plus" aria-hidden="true"></i>
          <span class="fs-it-btn-vertical-line"></span>
          Add a friend
        </button>
      <% end %>
    <% end %>
  </div>
</div>
<div class="bottom-img-profile" style="background: linear-gradient(white, rgb(255,255,255), transparent), url(<%= image_path('city.png') %>);">
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>