config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#intro'
  get '/map' => 'pages#home'
  get '/profile', to: "pages#profile"
  devise_for :users
  resources :users, only: [:edit, :update, :delete, :show, :index] do
    resources :friends, only: [:create, :destroy]
  end
  resources :friends, only: [:update]
  resources :routes
  resources :nodes
  resources :events, only: [:index, :show, :create, :edit, :destroy ] do
  resources :participants, only: [:create, :destroy]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="d-flex justify-content-between w-100 navbar-lewagon <%= 'trans' if action_name == 'home' || action_name == 'intro' || action_name == 'profile' %>">
  <div>
    <div class="button_container" id="toggle">
      <span class="top"></span>
      <span class="middle"></span>
      <span class="bottom"></span>
    </div>
  </div>
  <div class="overlay" id="overlay">
    <nav class="overlay-menu">
     <ul>
       <li><%= link_to "Generate", map_path, class: "bungee-font-nav" %></li>
       <li><%= link_to "Events", events_path, class: "bungee-font-nav" %></li>
       <% if user_signed_in? %>
         <li><%= link_to "Profile", profile_path, class: "bungee-font-nav" %></li>
         <li><%= link_to "Find runners", users_path, class: "bungee-font-nav" %></li>
         <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "bungee-font-nav"%></li>
       <% else %>
         <li><%= link_to "Login", new_user_session_path, class: "bungee-font-nav" %></li>
       <% end %>
     </ul>
    </nav>
  </div>
  <div class="logo-position">
    <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "MaxLogo.png" %>
    <% end %>
  </div>
</div>