config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#intro'
  get '/map' => 'pages#home'
  get '/profile', to: "pages#profile"
  devise_for :users
  resources :users, only: [:edit, :update, :delete, :show, :index] do
    resources :friends, only: [:create, :destroy]
  end
  resources :friends, only: [:update]
  resources :routes
  resources :nodes
  resources :events, only: [:index, :show, :create, :edit, :destroy ] do
  resources :participants, only: [:create, :destroy]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :route
  has_one_attached :photo
  has_many :participants, dependent: :destroy
  has_many :users, through: :participants, dependent: :destroy
  validates :description, :starttime, :title, presence: true


  def show_title
    return title.length > 24 ? "#{title.first(20)}..." : title;
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @today_events = Event.where("starttime between ? and ?", DateTime.now().to_date, (DateTime.now() + 1).to_date)
    @next_events = Event.where("starttime between ? and ?", (DateTime.now() + 1).to_date, (DateTime.now() + 7).to_date)
  end

  def show
    @event = Event.find(params[:id])
    @participants = @event.users
    @participant = Participant.where(event: @event, user: current_user)[0]

    @paths = []
      route = @event.route
      @nodes = route.nodes
      @markers = []
      @nodes.each do |node|
        @markers << {
          lat: node.latitude,
          lng: node.longitude
        } if node.real
      end
      if route.form == "Circular"
        @nodes.each_with_index do |node, index|
          response = RestClient.get "https://api.mapbox.com/directions/v5/mapbox/cycling/#{@nodes[index-1].longitude},#{@nodes[index-1].latitude};#{node.longitude},#{node.latitude}?geometries=geojson&exclude=ferry&access_token=#{ENV['MAPBOX_API_KEY']}"
          repos = JSON.parse(response) # => repos is an `Array` of `Hashes`.
          @paths << (repos['routes'].first['geometry']['coordinates'])
        end
      else
        number = 1
        while number < @nodes.length do
          response = RestClient.get "https://api.mapbox.com/directions/v5/mapbox/cycling/#{@nodes[number-1].longitude},#{@nodes[number-1].latitude};#{@nodes[number].longitude},#{@nodes[number].latitude}?geometries=geojson&exclude=ferry&access_token=#{ENV['MAPBOX_API_KEY']}"
          repos = JSON.parse(response) # => repos is an `Array` of `Hashes`.
          @paths << (repos['routes'].first['geometry']['coordinates'])
          number += 1
        end
      end

  end

  def create
    params[:event][:route] = Route.find(params[:event][:route])
    event = Event.new(require_params)
    event.route = params[:event][:route]
    participant = Participant.new
    if event.save
      participant.user = current_user
      participant.event = event
      participant.save
      redirect_to event_path(event)
    else
      render profile_path
    end
  end
  
  private
  def require_params
    params.require(:event).permit([:title, :description, :starttime, :route, :photo])
  end
end

app/views/events/index.html.erb
<div class="image-background-card">
  <div class="title-background">
    <h1 class="bungee-font-title"><strong>Events</strong></h1>
  </div>
</div>
<div class="container justify-content-center">
  <div>
    <h2 class="events-title"><strong>Today's runs</strong>  </h2>
  </div>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <% @today_events.each do |event| %>
        <div class="carousel-item <%= 'active' if event == @today_events.first %>">
          <a href="/events/<%= event.id %>">
            <card class="d-block w-100">
              <div class="card-event-lg">
                <% if event.photo.attached? %>
                  <%= cl_image_tag(event.photo.key, width: 480, height: 300, crop: :fill, id: "card-event-img") %>
                <% else %>
                  <%= image_tag "test_6.jpg", width: 400, height: 300, id: "card-event-img" %>
                <% end %>
                <% if event == @today_events.first %>
                <% end %>
                <div class="card-event-lg-info">
                  <h2><%= event.show_title %></h2>
                  <p> <i class="fas fa-map-marker-alt"></i> <%= event.route.nodes.first.address %> </p>
                  <p> Distance: <%= event.route.distance %>m</p>
                  <p> <i class="fas fa-user-plus mb-2"></i> <%= event.users.count  %></p>
                  <div class="div-size">
                    <div id="image-list" class="d-flex">
                      <% event.users.each do |user| %>
                        <div>
                        <% if user.photo.attached? %>
                              <%= cl_image_tag(user.photo.key, height: 30, width: 30, crop: :fill, class: "rounded-circle mr-1") %>
                            <% else %>
                              <%= image_tag("pp.png", crop: :fill, height: 30, width: 30, class: "rounded-circle")%>
                            <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                  <%# if event == @today_events.first %>
                  <%# end %>
                </div>
              </div>
            </card>
          </a>
        </div>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <h2 class="events-title-week"> Coming up this week..</h2>
  <div class="container">
    <% @next_events.each do |event| %>
      <a href="/events/<%= event.id %>">
        <div class="event-new-version">
          <div class="card-image">
            <% if event.photo.attached? %>
              <%= cl_image_tag(event.photo.key, width: 400, height: 300, crop: :fill) %>
            <% else %>
              <%= image_tag "test_6.jpg", width: 400, height: 300 %>
            <% end %>
            <div class="card-event-info">
              <div class="card-content">
                <h2><%= event.title %></h2>
                <!-- double check if necessary -->
                <!-- <div class="inline-avatar-lg div-size-events-show">
                  <ul>
                    <% event.users.first(5).each do |user| %>
                        <li>
                          <% if user.photo.attached? %>
                            <%= cl_image_tag(user.photo.key, crop: :fill, style:"height: 30px; width: 30px; margin-top:0 !important; margin-left: 5px; margin-bottom: 5px; ") %>
                          <% else %>
                            <%= image_tag("pp.png", crop: :fill, style:"height: 30px; width: 30px; margin-top:0 !important; margin-left: 5px; margin-bottom: 5px; ") %>
                          <% end %>
                          </li>
                    <% end %>
                  </ul>
                </div> -->
                <p>When: <%= event.starttime.strftime("%B %d, %Y at %I:%M%p") %> </p>
                <p> Distance:  <%= event.route.distance %> meters </p>
              </div>
            </div>
        </div>
        </div>
      </a>
    <% end %>
  </div>
</div>
<div class="bottom-img-profile" style="background: linear-gradient(white, rgb(255,255,255), transparent), url(<%= image_path('city.png') %>);">
</div>

app/views/events/show.html.erb
<h2 class="events-title-page"><%= @event.title %></h2>
<div class="event_cover">
  <div id="mapa"
  style="margin-bottom: 15px;"
  data-path="<%= @paths.to_json %>"
  data-node="<%= @nodes.first.to_json %>"
  data-markers="<%= @markers.to_json %>"
  data-zoom_size="12"
  data-zoom_time="1500"></div>
</div>
<div>
  <p><strong><i class="fas fa-map-marker-alt"></i></strong>  <%= @event.route.nodes.first.address %></p>
  <p><strong><i class="fas fa-running"></i></strong>  <%= @event.route.display_distance %> </p>
  <p><strong><i class="fas fa-clock"></i></strong>  <%= @event.starttime.strftime("%B %d, %Y at %I:%M%p") %></p>
  <p id="amount"><i class="fas fa-users"></i>  <%= @event.participants.count %></p>
  <div class="div-size">
      <div id="image-list" class="d-flex">
        <% @event.users.each do |user| %>
          <div>
           <% if user.photo.attached? %>
                <%= cl_image_tag(user.photo.key, height: 30, width: 30, crop: :fill, class: "rounded-circle mr-3") %>
              <% else %>
                <%= image_tag("pp.png", crop: :fill, height: 30, width: 30, class: "rounded-circle")%>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>
</div>
<div class="join-container mb-5">
  <div class="row fuck-off-bootstrap">
    <div class="col-md-12" id="join-button">
      <% if @participant.present? %>
        <%= link_to event_participant_path(participant_id: @participant.id, event_id: @event.id), method: :delete, remote: true do  %>
          <button class="btn btn-default charcoal-circle-button-red">Leave<span class="charcoal-circle-greater-than-red"></span></button>
          <% end %>
        <% else %>
        <%= link_to event_participants_path([@event, @participant]), method: :post, remote: true do  %>
          <button class="btn btn-default charcoal-circle-button">Join<span class="charcoal-circle-greater-than"></span></button>
        <% end %>

      <% end %>
    </div>
  </div>
</div>
<div class="bottom-img-profile" style="background: linear-gradient(white, rgb(255,255,255), transparent), url(<%= image_path('city.png') %>);">
</div>