config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#intro'
  get '/map' => 'pages#home'
  get '/profile', to: "pages#profile"
  devise_for :users
  resources :users, only: [:edit, :update, :delete, :show, :index] do
    resources :friends, only: [:create, :destroy]
  end
  resources :friends, only: [:update]
  resources :routes
  resources :nodes
  resources :events, only: [:index, :show, :create, :edit, :destroy ] do
  resources :participants, only: [:create, :destroy]
  end
end

app/views/pages/_friends.html.erb
<% user.friend_list.each do |f| %>
    <div class="big-card-profile">
      <a href="/users/<%= f.friend(user).id%>">
        <div class="card-event-profile">
          <% if f.friend(user).photo.attached? %>
            <%= cl_image_tag(f.friend(user).photo.key, width: 600, height: 500, crop: :fill) %>
          <% else %>
            <%= image_tag("pp.png", width: 600, height: 500, crop: :fill)%>
          <% end %>
          <div class="card-event-info h-100 p-2">
            <h4><%= f.friend(user).name.capitalize %> <%= f.friend(user).lastname.capitalize %> </h4>
            <div class="justify-content-between">
              <p> Username: <%= f.friend(user).username.capitalize %> </p>
              <p><%= f.friend(user).email %> </p>
            </div>
          </div>
        </div>
      </a>
    </div>
  <% end %>

app/views/pages/home.html.erb
<div class="container flex-direction-column justify-content-center">
  <div class="text-center">
    <%= form_for @new_node do |f|%>
      <div class="search-container h-100">
        <div class="d-flex justify-content-center h-100">
          <div class="searchbar">
            <%= f.text_field :address, autocomplete: 'off', class: "search_input", placeholder: "Search location" %>
            <button type="submit" class="search_icon"><i class="fas fa-search"></i></button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if @route %>
  <div class="bottom-choices center-route">
    <h3 class="m-1 mt-4"><i class="fas fa-running"></i> <%= @route.display_distance %>   ||   <i class="far fa-clock"></i> <%= @route.display_time %></h3>
    <%= link_to "Shuffle route", edit_route_path(@route), class: "btn btn-dark m-1 text-light", remote: true %>
    <%= link_to "Save route", profile_path, class: "btn btn-dark m-1 text-light" %>
    <a class="btn btn-dark m-1 text-light" href=<%=@route.build_google%> target="_blank">Follow in google maps</a>
  </div>
  <% else %>
  <div class="bottom-choices center-route">
    <h3 class="m-1 mt-4"><i class="fas fa-running"></i> ||  <i class="far fa-clock"></i></h3>
    <%= "Please search for a start point for your run"%>
  </div>
  <% end %>
</div>

</div>
<div id="home-map">
  <div id="mapa"
    data-path="<%= @paths.to_json %>"
    data-node="<%= @nodes.first.to_json %>"
    data-markers="<%= @markers.to_json %>"
    data-zoom_size="13"
    data-zoom_time="<%= @zoom_time %>">
  </div>
</div>

app/views/pages/intro.html.erb
<div class="image-background-home another-gradient">
  <div class="container center mt-5">
      <h2 class="bungee-font-home center-style">A <strong class='color-change'>ROUTE</strong> LIKE NO OTHER</h2>
      <br>
      <div class="container flex-direction-column justify-content-center">
        <div class="home-box-center">
          <%= form_for @new_node do |f|%>
          <div class="search-box-home">
          <%= f.text_field :address, class: "search-input-home", placeholder: "e.g. London NW3" %>
          </div>
          <div class="search-home">
            <button type="submit" class="btn search-button-home">GET YOUR ROOTY!</button>
          </div>
          <% end %>
        </div>
      </div>
  </div>
  <div class="home-review">
    <p class="review-text">"the best running app I've ever used!"</p>
    <p class="bungee-font-name"><strong>- Max Denton</strong></p>
  </div>
  <div class="black-box">
    <div class="center-style">
      <h2 class="bungee-font-how-to center-style">HOW IT WORKS</h2>
    </div>
    <div class="white-underline-home">
    </div>
    <p class="bungee-font-p center-style">1. <strong class='color-change-p'>Generate</strong> your Route</p>
    <p class="bungee-font-p center-style">2. <strong class='color-change-p'>Share </strong>your Routes with friends</p>
    <p class="bungee-font-p center-style">3. invite your <strong class="color-change-p">friends</strong> to join!</p>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="d-flex background-profile-page" style="background:linear-gradient(135deg, #add8e6, #b19cd9)">
</div>
<div class="profile-card">
  <% if current_user.photo.attached? %>
    <%= cl_image_tag(current_user.photo.key, class: "clip_path") %>
  <% else %>
    <%= image_tag "pp.png", crop: :fill, class: "clip_path"%>
  <% end %>
  <h2 class="username-profile">@<%= current_user.username %></h2>
  <p class="fullname-profile"><%= current_user.name %> <%= current_user.lastname %></p>
</div>
</br>
<div class="modal fade" id="exampleModal" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create your event!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <%= simple_form_for @event do |f| %>
        <%= f.input :title, placeholder: "Name" %>
        <%= f.input :description, placeholder: "Enter route description" %>
        <%= f.input :starttime, as: :string, input_html: {class: "datepicker"} %>
        <%= f.hidden_field :route %>
        <%= f.input :photo, label: "Choose a nice picture",
                    as: :file,
                    input_html: { multiple: false } %>
        <div class="modal-footer">
          <%= f.submit value: "Create event!", class: "btn btn-primary rounded" %>
          <% end %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

<nav>
  <div class="d-flex justify-content-center"><h2 class="bungee-font-small">My routes</h2></div>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-runs-tab" data-toggle="tab" href="#nav-runs" role="tab" aria-controls="nav-runs" aria-selected="true">Runs</a>
    <a class="nav-item nav-link" id="nav-events-tab" data-toggle="tab" href="#nav-events" role="tab" aria-controls="nav-events" aria-selected="false">Events</a>
    <a class="nav-item nav-link" id="nav-notifications-tab" data-toggle="tab" href="#nav-notifications" role="tab" aria-controls="nav-notifications" aria-selected="false">Notifications</a>
    <a class="nav-item nav-link" id="nav-friends-tab" data-toggle="tab" href="#nav-friends" role="tab" aria-controls="nav-friends" aria-selected="false">Friends</a>
  </div>
</nav>
</br>

<div class="tab-content tab-scroll" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-runs" role="tabpanel" aria-labelledby="nav-runs-tab">
    <div class="container">
      <div class="title-left m-3">
        <div class="routes_history_card">
          <% @routes.last(3).each do |r| %>
            <div class="big-card-profile">
              <a href="/map?route=<%= r.id%>&distance=5&zoom=1500">
                <div class="card-history-profile">
                  <%= image_tag "test_map.jpg" %>
                  <div class="card-history-info flex-grow-1">
                    <div>
                      <p><strong> Distance: </strong> <%= r.display_distance %></p>
                      <p><strong> From: </strong> <%= r.starting %> </p>
                      <p><strong> To: </strong> <%= r.ending %> </p>
                    </div>
                  </div>
                </div>
              </a>
              <button type="button" class="event-creator btn btn-primary w-100" data-toggle="modal" data-route="<%= r.id %>" data-target="#exampleModal">
                  Make it an event!
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="tab-pane fade transparent-tab" id="nav-events" role="tabpanel" aria-labelledby="nav-events-tab">
      <div class="container">
          <div class="title-left m-3">
              <div class="routes_history_card">
                  <% @events.each do |e| %>
                      <div class="big-card-profile">
                      <a href="/events/<%= e.id%>">
                          <div class="card-event-profile">
                            <% if e.photo.attached? %>
                              <%= cl_image_tag(e.photo.key, width: 600, height: 500, crop: :fill) %>
                            <% else %>
                              <%= image_tag "test_6.jpg", width: 600, height: 500 %>
                            <% end %>
                              <div class="card-event-info h-100 p-2">
                                  <div>
                                      <h5><strong> <%= e.title %> </strong></h5>
                                  </div>
                                  <div class="d-flex justify-content-between">
                                      <p><strong>Distance: </strong><%= e.route.display_distance %> </p>
                                      <p><strong> From: </strong> <%= e.route.nodes.first.address.upcase %> </p>
                                      <p><strong> To: </strong> <%= e.route.form == "Circular" ? e.route.nodes.first.address.upcase : e.route.nodes.last.address.upcase %> </p>
                                  </div>
                              </div>
                          </div>
                      </a>
                      </div>
                  <% end %>
              </div>
          </div>
      </div>
  </div>

  <div class="tab-pane fade transparent-tab" id="nav-notifications" role="tabpanel" aria-labelledby="nav-notifications-tab">
      <div class="container">
          <div class="title-left m-3">
              <div class="routes_history_card">
                <% @requests.each do |r| %>
                    <div class="big-card-profile">
                        <div class="card-event-profile">
                          <% if r.sender.photo.attached? %>
                            <%= cl_image_tag(r.sender.photo.key, width: 600, height: 500, crop: :fill) %>
                          <% else %>
                            <%= image_tag "pp.png", width: 600, height: 500, crop: :fill %>
                          <% end %>
                            <div class="card-event-info h-100 p-2">
                                <div>
                                    <h4><strong> <%= r.sender.username %> </strong></h4>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <p> <%= r.sender.name.capitalize %> <%= r.sender.lastname.capitalize %></p>
                                </div>
                                <%= link_to friend_path(r.user_id), method: :patch, remote: true do %>
                                  <button type="button" class="btn bg-blue fs-it-btn">
                                    <i class="fas fa-check"></i>
                                    Accept friend
                                  </button>
                                <% end %>
                            </div>
                        </div>
                    </div>
                  <% end %>
              </div>
          </div>
      </div>
  </div>

  <div class="tab-pane fade transparent-tab" id="nav-friends" role="tabpanel" aria-labelledby="nav-friends-tab">
    <div class="container">
      <div class="title-left m-3">
        <div class="routes_history_card" id="friendslist">
          <% current_user.friend_list.each do |f| %>
            <div class="big-card-profile">
              <a href="/users/<%= f.friend(current_user).id%>">
                <div class="card-event-profile">
                  <% if f.friend(current_user).photo.attached? %>
                    <%= cl_image_tag(f.friend(current_user).photo.key, width: 600, height: 500, crop: :fill) %>
                  <% else %>
                    <%= image_tag("pp.png", width: 600, height: 500, crop: :fill)%>
                  <% end %>
                  <div class="card-event-info h-100 p-2">
                    <h4><%= f.friend(current_user).name.capitalize %> <%= f.friend(current_user).lastname.capitalize %> </h4>
                    <div class="justify-content-between">
                      <p> Username: <%= f.friend(current_user).username.capitalize %> </p>
                      <p><%= f.friend(current_user).email %> </p>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="bottom-img-profile" style="background: linear-gradient(white, rgb(255,255,255), transparent), url(<%= image_path('city.png') %>);">
</div>